# Generated by Django 3.2.7 on 2021-10-25 09:27

import datetime
import django.core.validators
from django.db import migrations, models
import students.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=60, validators=[django.core.validators.MinLengthValidator(2)])),
                ('last_name', models.CharField(max_length=80, validators=[django.core.validators.MinLengthValidator(2)])),
                ('email', models.EmailField(max_length=120, null=True, unique=True, validators=[students.validators.no_elon_validator, students.validators.no_blacklist_email])),
                ('birthdate', models.DateField(default=datetime.date.today, null=True, validators=[students.validators.age_valid])),
                ('phone_number', models.CharField(max_length=14, null=True, unique=True, validators=[django.core.validators.RegexValidator('\\d{10,14}')])),
                ('enroll_date', models.DateField(default=datetime.date.today, null=True)),
                ('graduate_date', models.DateField(default=datetime.date.today, null=True)),
            ],
        ),
    ]
