# Generated by Django 3.2.7 on 2021-11-25 08:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='start_date',
            field=models.DateField(default=datetime.date(2021, 11, 25), null=True),
        ),
    ]
