# Generated by Django 3.2.7 on 2021-11-12 11:53

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_course_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='start_date',
            field=models.DateField(default=datetime.date(2021, 11, 12), null=True),
        ),
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('5321d4bf-accf-4006-b663-24e2fcbd0e46'), editable=False, primary_key=True, serialize=False, unique=True)),
                ('invited_st_first_name', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2)])),
                ('invited_st_last_name', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2)])),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.course')),
                ('inviter_student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.student')),
            ],
        ),
    ]
