# Generated by Django 3.2.7 on 2021-11-12 12:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_auto_20211112_1416'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invite',
            old_name='count',
            new_name='count_invites',
        ),
        migrations.AlterField(
            model_name='invite',
            name='id',
            field=models.UUIDField(default=uuid.UUID('498a4e84-1d7a-4a83-907f-c85c31e02a06'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
