# Generated by Django 3.2.7 on 2021-10-25 09:27

from django.db import migrations, models
import teachers.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('classroom_number', models.IntegerField(null=True)),
                ('phone_number', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=120, null=True, unique=True, validators=[teachers.validators.no_blacklist_email])),
            ],
        ),
    ]
