# Generated by Django 3.2.7 on 2021-10-11 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='cabinet_number',
            new_name='classroom_number',
        ),
    ]
