# Generated by Django 3.2.7 on 2021-10-12 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_remove_teacher_classroom_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='classroom_number',
            field=models.IntegerField(null=True),
        ),
    ]
