# Generated by Django 3.2.7 on 2021-10-12 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0004_teacher_classroom_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='subject_name',
            new_name='phone_number',
        ),
    ]
