# Generated by Django 3.2.7 on 2021-10-11 07:29

from django.db import migrations, models
from groups.models import Group


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=80, null=True)),
                ('number_of_students', models.CharField(max_length=80, null=True)),
                ('average_score', models.DecimalField(decimal_places=1, max_digits=3, null=True)),
            ],
        ),
        migrations.RunPython(Group.generate_groups)
    ]
