## Generated by Django 3.2.7 on 2021-10-06 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_A', models.CharField(max_length=20)),
                ('group_B', models.CharField(max_length=20)),
            ],
        ),
    ]
