# Generated by Django 3.2.7 on 2021-10-07 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='group_A',
        ),
        migrations.RemoveField(
            model_name='group',
            name='group_B',
        ),
        migrations.AddField(
            model_name='group',
            name='average_score',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='group_name',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='number_of_students',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
