# Generated by Django 3.2.7 on 2021-10-12 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_rename_group_name_group_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='number_of_students',
            field=models.IntegerField(null=True),
        ),
    ]
