# Generated by Django 3.2.7 on 2021-10-19 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_auto_20211007_1109'),
        ('groups', '0003_alter_group_number_of_students'),
    ]

    operations = [
    ]
